<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="w3c_td" nsURI="http://smar2t.org/models/w3c_td" nsPrefix="W3CTD">
  <eSubpackages name="core" nsURI="http://smar2t.org/models/w3c_td/core" nsPrefix="W3cTd">
    <eClassifiers xsi:type="ecore:EClass" name="Thing">
      <eAnnotations source="http://www.obeo.fr/dsl/dnc/archetype">
        <details key="archetype" value="Role"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="semanticContext" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="semanticType" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="created" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="modified" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="support" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="base" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="security" lowerBound="1"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
          eType="#//hypermediacontrols/Link" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="forms" upperBound="-1"
          eType="#//hypermediacontrols/Form"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="version" eType="#//core/VersionInfo"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="titles" upperBound="-1"
          eType="#//core/MultiLanguage"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="descriptions" upperBound="-1"
          eType="#//core/MultiLanguage" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="events" upperBound="-1"
          eType="#//core/StringToEventMap" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
          eType="#//core/StringToActionMap" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
          eType="#//core/StringToPropertyMap" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VersionInfo">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="instance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PropertyAffordance" eSuperTypes="#//core/InteractionAffordance">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="observable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InteractionAffordance" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="forms" lowerBound="1"
          upperBound="-1" eType="#//hypermediacontrols/Form" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="titles" eType="#//core/MultiLanguage"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="descriptions" eType="#//core/MultiLanguage"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EventAffordance" eSuperTypes="#//core/InteractionAffordance"/>
    <eClassifiers xsi:type="ecore:EClass" name="ActionAffordance" eSuperTypes="#//core/InteractionAffordance">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="safe" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="idempotent" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MultiLanguage"/>
    <eClassifiers xsi:type="ecore:EClass" name="StringToEventMap" instanceClassName="java.util.Map$Entry">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1"
          eType="#//core/EventAffordance" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StringToActionMap" instanceClassName="java.util.Map$Entry">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1"
          eType="#//core/ActionAffordance" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StringToPropertyMap" instanceClassName="java.util.Map$Entry">
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1"
          eType="#//core/PropertyAffordance" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="hypermediacontrols" nsURI="http://smar2t.org/models/w3c_td/hypermediacontrols"
      nsPrefix="W3cTd">
    <eClassifiers xsi:type="ecore:EClass" name="Link">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="href" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="rel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="anchor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Form">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" lowerBound="1" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="[&quot;readProperty&quot;, &quot;writeProperty&quot;]"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="href" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="contentType" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="application/json"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="contentCoding" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="subprotocol" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="security" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="scopes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="response" eType="#//hypermediacontrols/ExpectedResponse"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExpectedResponse">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="contentType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="dataschema" nsURI="http://smar2t.org/models/w3c_td/dataschema"
      nsPrefix="W3cTd">
    <eClassifiers xsi:type="ecore:EClass" name="DataSchema" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="semanticType" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="oneOf" upperBound="-1"
          eType="#//dataschema/DataSchema"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="titles" upperBound="-1"
          eType="#//core/MultiLanguage"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="descriptions" upperBound="-1"
          eType="#//core/MultiLanguage"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="const" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//AnySimpleType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="readOnly" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="writeOnly" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="format" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArraySchema" eSuperTypes="#//dataschema/DataSchema">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="minItems" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//UnsignedInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxItems" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//UnsignedInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
          eType="#//dataschema/DataSchema" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ObjectSchema" eSuperTypes="#//dataschema/DataSchema">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="required" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
          eType="#//dataschema/DataSchema" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StringSchema" eSuperTypes="#//dataschema/DataSchema"/>
    <eClassifiers xsi:type="ecore:EEnum" name="NewEnum1"/>
    <eClassifiers xsi:type="ecore:EClass" name="BooleanSchema" eSuperTypes="#//dataschema/DataSchema"/>
    <eClassifiers xsi:type="ecore:EClass" name="NumberSchema" eSuperTypes="#//dataschema/DataSchema">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimum" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Double"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximum" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Double"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IntegerSchema" eSuperTypes="#//dataschema/DataSchema">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimum" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximum" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NullSchema" eSuperTypes="#//dataschema/DataSchema"/>
  </eSubpackages>
  <eSubpackages name="security" nsURI="http://smar2t.org/models/w3c_td/security" nsPrefix="W3cTd">
    <eClassifiers xsi:type="ecore:EClass" name="SecurityScheme" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="semanticType" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="proxy" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//AnyURI"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="scheme" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="descriptions" eType="#//core/MultiLanguage"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NoSecurityScheme" eSuperTypes="#//security/SecurityScheme"/>
    <eClassifiers xsi:type="ecore:EClass" name="BasicSecurityScheme" eSuperTypes="#//security/SecurityScheme">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="in" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DigestSecurityScheme" eSuperTypes="#//security/SecurityScheme">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="qop" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="in" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="APIKeySecurityScheme" eSuperTypes="#//security/SecurityScheme">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="in" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BearerSecurityScheme" eSuperTypes="#//security/SecurityScheme">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="authorization" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//AnyURI"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="alg" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="format" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="in" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CertSecurityScheme" eSuperTypes="#//security/SecurityScheme">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="identity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PSKSecurityScheme" eSuperTypes="#//security/SecurityScheme">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="identity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PublicSecurityScheme" eSuperTypes="#//security/SecurityScheme">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="identity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PoPSecurityScheme" eSuperTypes="#//security/SecurityScheme">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="authorization" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//AnyURI"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="alg" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="format" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="in" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//AnyURI"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OAuth2SecurityScheme" eSuperTypes="#//security/SecurityScheme">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="authorization" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//AnyURI"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="token" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//AnyURI"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="refresh" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//AnyURI"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="scopes" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//AnyURI"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="flow" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
